# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Isaac's Journey in Tech
email: cxx7821@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Isaac's Tech Corner, a blog dedicated to exploring the
  intricacies of motor control and the fascinating world of programming. Here,
  you'll find in-depth articles, insightful tutorials, and handy tips and tricks.
baseurl: "/Isaac-Journey-in-Tech-blog" # the subpath of your site, e.g. /blog
url: "https://chen-isaac.github.io" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: isaac-xinxi-chen
github_username:  Chen-Isaac


# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
